const allQuestions = [
	"What do you do, and how long have you been doing it?",
	"Where are you from originally?",
	"Where did you go to school?",
	"What was your major?",
	"Who has been the biggest influence on your life?",
	"What's your favorite place in the entire world?",
	"What really makes you laugh?",
	"Are there any foods you absolutely hate?",
	"What's your favorite movie of all time?",
	"What's your favorite book of all time? ",
	"What's your biggest goal right now?",
	"What's your favorite way to spend a weekend?",
	"What was your family like growing up?",
	"What were you like as a kid?",
	"What should I know about you that I would never think to ask about?",
	"What do you love to do when you're not working?",
	"What's your favorite TV show right now? ",
	"What type of music do you like?",
	"Have you traveled anywhere really cool lately?",
	"Are you more of a cat or a dog person? Both? Neither?",
	"What is your absolute favorite food?",
	"Who's your biggest role model?",
	"What's your biggest pet peeve?",
	"What is your favorite candy?",
	"What is your favorite dessert? ",
	"If you won the lottery, what is the first thing you'd do with the money?",
	"Is there anywhere else you would love to live, other than here?",
	"What's on your bucket list?",
	"Are you a morning or a night person?",
	"Do you enjoy cooking?",
	"What's your favorite thing about your job?",
	"What's your least favorite thing about your job?",
	"What is your favorite flavor of ice cream?",
	"What combination of toppings makes your perfect pizza?",
	"Do you drink? ",
	"Where would you most like to visit that you've never been?",
	"What is the most thoughtful gift you've ever received?",
	"If you could spend the day with one celebrity, who would it be?",
	"If you could be any person for a day, who would it be?",
	"What do you feel most passionate about?",
	"What's something you've been really proud of lately?",
	"What's something you've always wanted to try?",
	"What do you like about dating?",
	"What is your least favorite thing about dating?",
	"What's something you're bad at?",
	"Who in your family are you closest to?",
	"What's your favorite holiday?",
	"What's one of your favorite childhood memories?",
	"What is your favorite thing to cook?",
	"What's your favorite piece of clothing that you own?",
	"What is something you are financially saving up for?",
	"What's a New Year's resolution you'd like to stick to?",
	"What is a job you would never do?",
	"What is your absolute dream job?",
	"What fact about you would surprise me the most?",
	"Do you consider yourself spontaneous, or a planner?",
	"What's the most spontaneous thing you've ever done?",
	"What is your favorite musical?",
	"Who's your favorite sports team?",
	"What quality for you is an automatic \"no way\" when pursuing someone in a relationship?",
	"How would your best friends describe you?",
	"Do you prefer salty or sweet snacks?",
	"What is the best single piece of advice you've ever received?",
	"What do you wish your 20 year old self would have known?",
	"If you could travel back and live in any period of time, when would it be?",
	"What has been your greatest achievement so far?",
	"What is a tradition your family had when you were a kid?",
	"What is a tradition you would hope to start with your future family?",
	"What is your most embarrassing moment?",
	"What is your love language?",
	"What do you like most about where you live?",
	"What was the worst job you've ever had?",
	"When you were a kid, what did you hope to do when you grew up?",
	"Who was your favorite teacher/professor and why?",
	"What is the luckiest thing that has ever happened to you?",
	"What is one skill you wish you could be better at?",
	"Do you have a big group of friends? ",
	"What's your favorite band?",
	"If your life was a movie, who would play you?",
	"If you could donate to any charity, which charity would it be and why?",
	"In one word, how would you describe yourself?",
	"If there could be one word to describe your life as a whole - which word?",
	"What do you most look for in a partner?",
	"What is your favorite physical feature about youself?",
	"If you could be any animal, which animal would you be?",
	"What is your biggest pet peeve?",
	"What was the last book you read?",
	"If you could have one super power, what would it be?",
	"What is the kindest thing you've ever done for someone else?",
	"What is your ideal vacation?",
	"What does your dream house look like?",
	"What do you think is your biggest strength?",
	"What is your favorite season of the year?",
	"What was your favorite childhood pastime? ",
	"What is something you wish more people knew about you?",
	"What is the most spontaneous thing you have ever done?",
	"Do you have any nicknames? ",
	"What is your favorite thing you've ever seen God do in your life?",
	"What would be a perfect day for you?",
	"For what in your life do you feel most grateful?",
];

function newQuestion() {
	let rand = Math.floor(Math.random() * allQuestions.length);

	document.getElementById("question").innerHTML = allQuestions[rand];
}

newQuestion();